name: Tests
on: 
  push:
    branches:
      -feats
  pull_request:
    branches:
      -develop
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: copy
      uses: actions/checkout@v3
      
    - name: python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: pytest
      run: pip install pytest
        
    - name: testing
      run: pytest